### ISSUE TITLE
Issue when using mod in my server

### ISSUE THREAD

**Issue by Tw1ntend0** [FrostbyteGames1/Frostbytes-Maximum-Mobility#1]
When I try to use this mod in my server, I get the following issue:
https://pastebin.com/yiXwWS92

**Comment by FrostbyteGames1** [comment]
What happens if you remove the file from the server (only run the mod on the client side)? Does the player start rubber-banding or does the mod work as expected?

**Comment by FrostbyteGames1** [comment]
Closed for now. Will reopen if issue persists.
