### ISSUE TITLE
Change fabricloader version on fabric.mod.json

### ISSUE THREAD

**Issue by mateus3c** [FrostbyteGames1/Frostbytes-Maximum-Mobility#2]
all your mods have their fabricloader depends on **"fabricloader": "0.14.21",**

that makes so your mods can only be loaded on that specific fabricloader version (crashes before game load on any other version)

you should change it to **"fabricloader": ">=0.14.21",**

that way it will be compatible with version 0.14.21 or higher

**Comment by FrostbyteGames1** [comment]
Fixed
