### ISSUE TITLE
Server Glitching with Boat Step Up

### ISSUE THREAD

**Issue by PowerGamer12** [FrostbyteGames1/Frostbytes-Maximum-Mobility#4]
Hi, 
I've been using your mod to help make interesting maps for boat races. However, on servers, I find that, when  approaching a block to step up at higher speeds, the boat glitches and refuses to step up at all. I have attached a video of what occurs when this happens.

https://github.com/FrostbyteGames1/Frostbytes-Maximum-Mobility/assets/173130151/9d1b57a3-947d-4754-874d-059760193556

**Comment by PowerGamer12** [comment]
I will also note, we have no anti-cheat or anything. I did not install it server side either. Could that potentially fix the issue?

**Comment by FrostbyteGames1** [comment]
> I did not install it server side either. Could that potentially fix the issue?

No, installing it on the server isn't supported and shouldn't be required. I will look into what might be causing this.

**Comment by PowerGamer12** [comment]
Just to clarify, I am using the latest 1.21 version.

**Comment by FrostbyteGames1** [comment]
After some testing, this bug appears to happen due to Minecraft's movement validation that happens on the server side. I have created a [server side mod](https://www.curseforge.com/minecraft/mc-mods/frostbytes-skip-server-movement-check) that should disable that validation check. (Make sure it is only installed on the server, not the client)

**Comment by PowerGamer12** [comment]
Awesome work! I'll give it a go some point soon and let yoy know if it works for me.

**Comment by FrostbyteGames1** [comment]
@PowerGamer12 Do you have an update on this?

**Comment by PowerGamer12** [comment]
Yep! It works perfectly. Sorry, haven't been able to test it because multiple issues came up over the last couple of weeks. But we put it on the server and everything is perfect noe
